name: CI
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    runs-on: ubuntu-latest
    name: "Test - crystal: ${{ matrix.crystal }}, MT: ${{ matrix.MT }}, stable: ${{ matrix.stable }}"
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - 1.3.2
        stable: [true]
        MT: [false]
        include:
          - crystal: 1.3.2
            MT: true
            stable: false
          - crystal: nightly
            MT: true
            stable: false
          - crystal: nightly
            MT: false
            stable: false
    services:
      rethink:
        image: rethinkdb:2.4
        ports:
          - 29015:29015
          - 28015:28015
    steps:
      - uses: actions/checkout@v2
      - name: Install crystal
        uses: crystal-lang/install-crystal@v1.6.0
        with:
          crystal: ${{ matrix.crystal }}
      - run: shards install --ignore-crystal-version
      - name: Test
        if: ${{ !matrix.MT }}
        run: crystal spec --error-trace -v --order=random --no-color
      - name: Test Multithreaded
        if: ${{ matrix.MT }}
        run: crystal spec --error-trace -v --order=random --no-color -Dpreview_mt

  publish:
    needs: test
    uses: PlaceOS/.github/.github/workflows/publish-crystal-docs.yml@main
