name: CI
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    uses: PlaceOS/.github/.github/workflows/containerised-test.yml@main
    with:
      cache_shards: false
      todo_issues: true
      first_commit: 804167d0d9b614ade1443ee6706a3f40a6b14cb1

  publish:
    needs: test
    uses: PlaceOS/.github/.github/workflows/publish-crystal-docs.yml@main
